### ISSUE TITLE
Rename `*.expected-data` to `*.overpassql`

### ISSUE THREAD

**Issue by FloEdelmann** [vmiklos/vmexam#10]
`*.overpassql` is now the recommended file extension for Overpass QL: [OSM Wiki: Overpass QL § File extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension)
*(**Disclaimer:** I added that section after [some discussion](https://wiki.openstreetmap.org/wiki/Talk:Overpass_API/Overpass_QL#Recommended_file_extension?).)*

I propose to rename all Overpass QL files in this repo to `*.overpassql` for consistency.

Context: GitHub's syntax highlighting engine requires that 200 repositories use the same file extension before they consider supporting that syntax and file extension: https://github.com/github/linguist/issues/5890

**Comment by vmiklos** [comment]
I would suggest to do this in https://github.com/vmiklos/osm-gimmisn, this repo is just a set of examples. Does that work for you?

**Comment by FloEdelmann** [comment]
Sure! Best would be changing it in both repos of course :wink: 

Please let me know when you use `*.overpassql` in another repository, so I can add it to the tracking list: https://github.com/users/FloEdelmann/projects/2

**Comment by vmiklos** [comment]
Fixed with f511124202c8a97bbac4f1fb4b8b16ca6d58f83f

**Comment by FloEdelmann** [comment]
Thanks for renaming!
